### ISSUE TITLE
Elaboration Requested for some steps

### ISSUE THREAD

**Issue by defencedog** [w568w/alarm_repo#2]
I am a chemical engineer by trade but am well-versed in compiling various python / cpython modules. I have OPI-3b with `DietPi` installed
```
OS: Debian GNU/Linux 11 (bullseye) aarch64
Host: Rockchip RK3566 OPi 3B
Kernel: 6.9.5-edge-rockchip64
Uptime: 7 hours, 25 mins
Packages: 804 (dpkg)
Shell: bash 5.1.4
Resolution: 1280x1024
Terminal: /dev/ttyS2
CPU: (4) @ 1.800GHz
Memory: 376MiB / 3733MiB

```

I am running educational server here can you help me compiling these Panfrost GPU drivers, becasue my KODI is heavily under performing

```
dietpi@DietPi:~$ glxinfo -B
name of display: :1
display: :1  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 11.0.1, 128 bits) (0xffffffff)
    Version: 20.3.5
    Accelerated: no
    Video memory: 3733MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 11.0.1, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 20.3.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.1 Mesa 20.3.5
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20


```

**Comment by w568w** [comment]
1. My first question is **where your kernel comes from**? I don't remember the official image released by OrangePi having a kernel version as high as 6.9.5.

2. The Panfrost driver is a kernel module, which means there are only two ways to compile it:
    1. I have **the exact same kernel** and its kernel headers as you, allowing me to compile it into a **distributable kernel module object file** (`.ko`);
        - And this is something I am unwilling to do. First, you are using Debian while I am using the ArchLinux ARM distribution. The two distributions manage kernels in completely different ways. ArchLinux ARM uses the Arch Build System to compile and install the kernel. You would need to provide me with information while simultaneously writing a `PKGBUILD` build script specifically for ArchLinux, and ensure that its output is exactly the same as that of the Debian build system. **This would waste a lot of time for both of us.**
    2. **Recompile your kernel by yourself** with the relevant options enabled during the build process so that the installed kernel has the Panfrost kernel module built-in.

p.s. It looks like you are following the "Open-sourced upstream solution" in my README. I need to remind you that the open-source solution is not very stable, has lower performance compared to the closed-source solution, and Panfrost only supports OpenGL ES, not OpenCL. **If you need OpenCL, your only option is the closed-source solution.**

**Comment by defencedog** [comment]
Thanks for taking time to educate me. 
- My .img comes from official [dietpi](https://dietpi.com/docs/hardware/) page for `Orangepi-3b`
- I am willing to take time to recompile kernel. Will that create some kind of `.deb` file that I can execute easily in my running OS (just like installing a setup file in Windows OS)
- In your instructions on main page you mentioned `userspace drivers`. To me it looks like a lot like Windows OS drivers where you load up operating system & then install hardware drivers (audio, GPU, BT). Is my understanding correct? 
- Will the high performing closed-source drivers always need Arch? Because on official OrangePI website they have Opi OS (Arch) as well as Debian & Ubuntu .img

**Comment by w568w** [comment]
> My .img comes from official [dietpi](https://dietpi.com/docs/hardware/) page for `Orangepi-3b`

Oh, I've never heard of it; looks a nice distro. I might give it a shot someday too. :smiley: 

> I am willing to take time to recompile kernel. Will that create some kind of `.deb` file that I can execute easily in my running OS (just like installing a setup file in Windows OS)

Yes, Linux kernel, as a Debian package (`.deb`), basically contains a kernel file and a flatten device tree file in `/boot`, and some module files in `/usr/lib/modules`. 

Installing a kernel is no different from installing a regular application like a web browser.

However, **I can't offer much help here.** The repository contains build scripts written for the Arch build system, which are not suitable for Debian or other distros. You'll need to find the tutorials yourself.

> * In your instructions on main page you mentioned `userspace drivers`. To me it looks like a lot like Windows OS drivers where you load up operating system & then install hardware drivers (audio, GPU, BT). Is my understanding correct?

No. On Linux, a "driver" often consists of two different parts: 

1. one is a **kernel module in the kernel** (responsible for direct hardware interaction, power management, and other basic functions), 
2. and the other is a **regular user-space library** (responsible for interacting with the kernel module and providing implementations for OpenGL ES and other functionalities). 

For example:

1. **Panfrost** is a kernel module that can start/stop the Opi3b's ARM Mali G52 GPU and execute basic instructions on it;
2. **Mesa** is a huge and universal userspace driver, containing many different userspace drivers, able to talk with Panfrost and provide OpenGL ES to your programs.

You need to install both to utilize the GPU for running OpenGL ES, OpenCL, etc. Additionally, these two parts of the driver must be compatible with each other, so you need to choose between the "open-source" and the "closed-source" solution.

> Will the high performing closed-source drivers always need Arch? Because on official OrangePI website they have Opi OS (Arch) as well as Debian & Ubuntu .img

No. As far as I know, the Debian, Ubuntu, and OpiOS (Arch) provided on the OrangePI official website **all have closed-source kernel modules**. You just need to go [here](https://github.com/orangepi-xunlong/rk-rootfs-build/tree/rk35xx_packages/common/) to install the corresponding userspace driver package `libmali-linux6.1`.

On the other hand, if you are adventurous, you can also [download the kernel module source from the ARM official website](https://developer.arm.com/downloads/-/mali-drivers/bifrost-kernel), compile, and install it yourself, so that you don't have to change your kernel or distro.

**Comment by defencedog** [comment]
Thanks for teaching me many things...

> You just need to go here to install the corresponding userspace driver package  `libmali-linux6.1`

I believe that the link you provided should be thisn one instead corresponding to [rk356x](https://github.com/orangepi-xunlong/rk-rootfs-build/tree/rk356x_packages) or is there a particular reason you choose `6.1` 

> compile, and install it yourself, so that you don't have to change your kernel or distro.

Will try on weekend! As I told earlier I have been compiling many `python / cython` stuff which never resulted in a binary `.deb` file but I believe the link you shared will get me started

Secondly can you see this 30 second [video](https://m.youtube.com/watch?si=Qqwaeo_FjEUvowa5&v=qlm1Zz0zdWQ&feature=youtu.be) segment from 0730-0830. The author [Joshua-Riek](https://github.com/Joshua-Riek) explains advantages & disadvantages of main-line versus close-source kernel. I believe for hardware compatibility & stability close-source perhaps is best choice

**Comment by w568w** [comment]
> I believe that the link you provided should be thisn one instead corresponding to [rk356x](https://github.com/orangepi-xunlong/rk-rootfs-build/tree/rk356x_packages) or is there a particular reason you choose `6.1`

Oops, I've made a mistake. Just use the link that you mentioned to `rk356x_packages`. You need to install driver for `Bifrost` GPU family rather than for `Valhall` family.
